package photorepository

import (
	"github.com/dstolbert/osutils"
	"github.com/sirupsen/logrus"
)

type repository struct {
	filepath string
	os       osutils.Osutils

	/*
		generate::components
		skipTestFile::true
	*/
}

type Params struct {
	Filepath string
	OS       osutils.Osutils
}

func (p *Params) Convert() *repository {

	r := repository{
		filepath: p.Filepath,
		os:       p.OS,
	}

	// does the dir exist?
	_, err := r.os.Stat(r.filepath)
	if err != nil {
		logrus.Panicf("could not initialize repo: %s", err.Error())
	}

	return &r
}

// Code below was generated by components. DO NOT EDIT.
// Component version: v0.1.0

type Repository interface {
	Get(firstName string, lastName string) (string, error)
}

func New(p Params) Repository {
	return p.Convert()
}
