package pdfcontroller

import "github.com/dstolbert/directory-generator/internal/repository/csvrepository"

type controller struct {
	/*
		generate::components
		skipTestFile::true
	*/

	output string
	csv    csvrepository.Repository
}

type Params struct {
	Output string
	CSV    csvrepository.Repository
}

func (p *Params) Convert() *controller {

	r := controller{
		csv:    p.CSV,
		output: p.Output,
	}

	return &r
}

// Code below was generated by components. DO NOT EDIT.
// Component version: v0.1.0

type Controller interface {
	SavePDF() error
}

func New(p Params) Controller {
	return p.Convert()
}
